apiVersion: v1
kind: Service
metadata:
  name: my-django-app-service
spec:
  type: LoadBalancer
  selector:
    app: my-django-app
  ports:
    - port: 80        # 你希望外部访问的端口
      targetPort: 8000  # 容器内部的端口，通常是 Django 监听的端口
      protocol: TCP
